# Generated by Django 4.2.3 on 2023-07-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "clientid",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("clientname", models.CharField(max_length=50)),
                ("clienttel", models.CharField(max_length=11)),
                ("clientaddr", models.CharField(max_length=50)),
            ],
        ),
    ]
